# Generated by Django 5.2.16 on 2026-08-12 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True, verbose_name='code')),
                ('name_uz', models.CharField(max_length=160, verbose_name='name in Uzbek')),
                ('name_ru', models.CharField(max_length=160, verbose_name='name in Russian')),
                ('name_en', models.CharField(max_length=160, verbose_name='name in English')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color in #RRGGBB format.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='color')),
                ('icon', models.SlugField(blank=True, max_length=48, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('requires_management_approval', models.BooleanField(default=False, verbose_name='requires management approval')),
                ('allows_emergency_override', models.BooleanField(default=False, verbose_name='allows emergency override')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'event type',
                'verbose_name_plural': 'event types',
                'ordering': ('sort_order', 'code'),
            },
        ),
    ]
