# Generated by Django 5.2.16 on 2026-08-12 12:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('planned_date', models.DateField(verbose_name='planned date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('zoom_url', models.URLField(blank=True, verbose_name='Zoom / Meeting URL')),
                ('registration_url', models.URLField(blank=True, verbose_name='Registration URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('cancelled', 'Cancelled'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('emergency', 'Emergency')], default='draft', max_length=24, verbose_name='status')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=24, verbose_name='priority')),
                ('expected_attendees', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='expected attendees')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventtype', verbose_name='event type')),
                ('management_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_events', to=settings.AUTH_USER_MODEL, verbose_name='management responsible')),
                ('organizing_organizations', models.ManyToManyField(blank=True, related_name='events', to='organizations.organization', verbose_name='organizing organizations')),
                ('responsible_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_events', to=settings.AUTH_USER_MODEL, verbose_name='responsible employee')),
                ('sponsors', models.ManyToManyField(blank=True, related_name='events', to='organizations.sponsor', verbose_name='sponsors')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_events', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='venues.venue', verbose_name='venue')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ('-planned_date', 'start_time', 'title'),
                'indexes': [models.Index(fields=['venue', 'planned_date', 'status'], name='events_even_venue_i_ae2834_idx'), models.Index(fields=['planned_date', 'status'], name='events_even_planned_887c31_idx'), models.Index(fields=['status', 'priority'], name='events_even_status_a70d1d_idx')],
            },
        ),
    ]
