# Generated by Django 5.2.16 on 2026-08-12 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='displaced_by_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displaced_events', to='events.event', verbose_name='displaced by event'),
        ),
        migrations.AddField(
            model_name='event',
            name='emergency_justification',
            field=models.TextField(blank=True, default='', verbose_name='emergency justification'),
        ),
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='rejection reason'),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reviewed at'),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='event',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency Override')], default='normal', max_length=24, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('planned', 'Planned'), ('displaced', 'Displaced by Emergency'), ('cancelled', 'Cancelled'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('emergency', 'Emergency')], default='draft', max_length=24, verbose_name='status'),
        ),
    ]
