# Generated by Django 5.2.16 on 2026-08-13 08:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_displaced_by_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title / position')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='organization')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/', verbose_name='photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('public_profile_enabled', models.BooleanField(default=True, verbose_name='public profile enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'speaker',
                'verbose_name_plural': 'speakers',
                'ordering': ('full_name',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_public_enabled',
            field=models.BooleanField(default=True, verbose_name='public page enabled'),
        ),
        migrations.AddField(
            model_name='event',
            name='program_intro',
            field=models.TextField(blank=True, default='', verbose_name='program intro'),
        ),
        migrations.AddField(
            model_name='event',
            name='program_notes',
            field=models.TextField(blank=True, default='', verbose_name='program notes'),
        ),
        migrations.AddField(
            model_name='event',
            name='program_pdf',
            field=models.FileField(blank=True, null=True, upload_to='event_programs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='program PDF'),
        ),
        migrations.AddField(
            model_name='event',
            name='program_source',
            field=models.CharField(choices=[('pdf', 'PDF File'), ('manual', 'Manual Agenda')], default='manual', max_length=12, verbose_name='program source'),
        ),
        migrations.AddField(
            model_name='event',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='public token'),
        ),
        migrations.CreateModel(
            name='EventProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('speaker_name_override', models.CharField(blank=True, default='', max_length=255, verbose_name='speaker name override')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='events.event', verbose_name='event')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_items', to='events.speaker', verbose_name='speaker')),
            ],
            options={
                'verbose_name': 'program item',
                'verbose_name_plural': 'program items',
                'ordering': ('sort_order', 'start_time'),
            },
        ),
    ]
