# Generated by Django 5.2.16 on 2026-08-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_speaker_event_is_public_enabled_event_program_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_closes_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='check-in closes at'),
        ),
        migrations.AddField(
            model_name='event',
            name='checkin_enabled',
            field=models.BooleanField(default=False, verbose_name='check-in enabled'),
        ),
        migrations.AddField(
            model_name='event',
            name='checkin_opens_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='check-in opens at'),
        ),
    ]
