# Generated by Django 5.2.16 on 2026-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_checkin_closes_at_event_checkin_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_visibility',
            field=models.CharField(choices=[('full', 'Full (Show Event Details)'), ('generic', "Generic (Show 'Private Meeting')"), ('hidden', 'Hidden (Show Occupied Only)')], default='full', max_length=16, verbose_name='display visibility'),
        ),
    ]
