# Generated by Django 5.2.16 on 2026-08-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_display_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_1d',
            field=models.BooleanField(default=True, verbose_name='1 day before'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_30m',
            field=models.BooleanField(default=True, verbose_name='30 minutes before'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_3d',
            field=models.BooleanField(default=True, verbose_name='3 days before'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_3h',
            field=models.BooleanField(default=True, verbose_name='3 hours before'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_7d',
            field=models.BooleanField(default=True, verbose_name='7 days before'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminders_enabled',
            field=models.BooleanField(default=True, verbose_name='Telegram reminders enabled'),
        ),
    ]
