# Generated by Django 5.2.16 on 2026-08-13 13:00

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_reminder_1d_event_reminder_30m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='program_pdf',
            field=models.FileField(blank=True, null=True, upload_to='event_programs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), config.validators.validate_pdf_upload], verbose_name='program PDF'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='speakers/', validators=[config.validators.validate_image_upload], verbose_name='photo'),
        ),
    ]
