# Generated by Django 5.2.16 on 2026-08-25 08:31

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_program_pdf_alter_speaker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/%Y/%m/', validators=[config.validators.validate_image_upload], verbose_name='event banner image'),
        ),
    ]
