# Generated by Django 5.2.16 on 2026-09-10 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_banner_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attending_doctors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'doctor'}, related_name='attending_events', to=settings.AUTH_USER_MODEL, verbose_name='speaker doctors'),
        ),
    ]
