# Generated by Django 5.2.16 on 2026-09-11 09:49

from django.db import migrations, models


def enable_checkin_for_existing_events(apps, schema_editor):
    """Bring previously-created events in line with the new default=True:
    check-in should be on unless a staff member explicitly turned it off."""
    Event = apps.get_model("events", "Event")
    Event.objects.filter(checkin_enabled=False).update(checkin_enabled=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_attending_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='checkin_enabled',
            field=models.BooleanField(default=True, verbose_name='check-in enabled'),
        ),
        migrations.RunPython(enable_checkin_for_existing_events, noop_reverse),
    ]
