# Generated by Django 5.2.16 on 2026-09-10 07:18

import config.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('international_admin', 'International Department Admin'), ('responsible_employee', 'Responsible Employee'), ('management_responsible', 'Management Responsible'), ('leadership_viewer', 'Leadership Viewer'), ('content_manager', 'Content / SMM Manager'), ('reception_operator', 'Reception / Check-in Operator'), ('doctor', 'Doctor')], default='responsible_employee', max_length=32),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=150, verbose_name='specialty')),
                ('workplace', models.CharField(max_length=200, verbose_name='workplace')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='position / academic degree')),
                ('phone', models.CharField(max_length=32, verbose_name='phone')),
                ('languages', models.CharField(blank=True, help_text='e.g. UZ, RU, EN', max_length=150, verbose_name='languages spoken')),
                ('license_number', models.CharField(blank=True, max_length=64, verbose_name='license / ID number')),
                ('bio', models.TextField(blank=True, verbose_name='short bio')),
                ('photo', models.ImageField(blank=True, upload_to='doctors/%Y/%m/', validators=[config.validators.validate_image_upload], verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'doctor profile',
                'verbose_name_plural': 'doctor profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('reason', models.TextField(verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_slots', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'staff unavailability',
                'verbose_name_plural': 'staff unavailability',
                'ordering': ('-start_date', '-start_time'),
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='accounts_st_user_id_61b47e_idx')],
            },
        ),
    ]
