# Generated by Django 5.2.16 on 2026-09-15 05:31

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_doctorprofile_staffunavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/', validators=[config.validators.validate_image_upload], verbose_name='avatar'),
        ),
    ]
