# Generated by Django 5.2.16 on 2026-09-19 20:13

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(max_length=32, validators=[config.validators.validate_phone_number], verbose_name='phone'),
        ),
    ]
