# Generated by Django 5.2.16 on 2026-09-21 05:21

from django.db import migrations, models


def backfill_approved_at_for_active_users(apps, schema_editor):
    """Accounts that are already active predate this field entirely — treat
    them as already-approved so a later deactivation doesn't make the login
    page wrongly claim their (already-decided) application is still pending."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_active=True, approved_at__isnull=True).update(
        approved_at=models.F("date_joined")
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_doctorprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When an administrator first activated this account.', null=True, verbose_name='approved at'),
        ),
        migrations.RunPython(backfill_approved_at_for_active_users, noop_reverse),
    ]
