# Generated by Django 5.2.16 on 2026-08-13 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_event_reminder_1d_event_reminder_30m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('telegram_channel', 'Telegram channel'), ('instagram', 'Instagram')], max_length=24)),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for approval'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('headline', models.CharField(max_length=180)),
                ('short_description', models.TextField(blank=True, default='')),
                ('caption', models.TextField(blank=True, default='')),
                ('rendered_caption', models.TextField(blank=True, default='')),
                ('banner_template', models.CharField(choices=[('conference', 'Conference'), ('symposium', 'Symposium'), ('seminar', 'Seminar'), ('delegation', 'Delegation Visit'), ('meeting', 'Meeting'), ('emergency', 'Emergency Announcement')], default='conference', max_length=24)),
                ('include_qr', models.BooleanField(default=True)),
                ('include_sponsors', models.BooleanField(default=True)),
                ('banner', models.ImageField(blank=True, upload_to='publications/%Y/%m/')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('external_post_id', models.CharField(blank=True, default='', max_length=255)),
                ('external_container_id', models.CharField(blank=True, default='', max_length=255)),
                ('external_url', models.URLField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_publications', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_publications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='events.event')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='publication_status_63a830_idx'), models.Index(fields=['platform', 'language'], name='publication_platfor_617c0e_idx')],
            },
        ),
    ]
