# Generated by Django 5.2.16 on 2026-08-13 13:00

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='banner',
            field=models.ImageField(blank=True, upload_to='publications/%Y/%m/', validators=[config.validators.validate_image_upload]),
        ),
    ]
