"""Update Phase 11 translations without requiring system GNU gettext on Windows."""

from pathlib import Path

import polib

TRANSLATIONS = {
    "Month": ("Oy", "Месяц"),
    "Week": ("Hafta", "Неделя"),
    "Day": ("Kun", "День"),
    "List": ("Ro‘yxat", "Список"),
    "events": ("tadbir", "мероприятий"),
    "Planned": ("Rejalashtirilgan", "Запланировано"),
    "Approved": ("Tasdiqlangan", "Согласовано"),
    "Available": ("Bo‘sh", "Свободен"),
    "Occupied": ("Band", "Занят"),
    "Upcoming": ("Tez orada", "Скоро"),
    "Event type": ("Tadbir turi", "Тип мероприятия"),
    "Priority": ("Ustuvorlik", "Приоритет"),
    "Role": ("Rol", "Роль"),
    "Activity": ("Faollik", "Активность"),
    "Connected": ("Ulangan", "Подключено"),
    "Not connected": ("Ulanmagan", "Не подключено"),
    "View all": ("Barchasini ko‘rish", "Смотреть все"),
    "Available venues": ("Bo‘sh zallar", "Свободные залы"),
    "Occupied venues": ("Band zallar", "Занятые залы"),
    "Seven-day calendar preview": (
        "Yetti kunlik taqvim ko‘rinishi",
        "Предпросмотр календаря на семь дней",
    ),
    "Calendar preview": ("Taqvim ko‘rinishi", "Предпросмотр календаря"),
    "Open interactive calendar": ("Interaktiv taqvimni ochish", "Открыть интерактивный календарь"),
    "Try again": ("Qayta urinish", "Повторить"),
    "Could not refresh data.": ("Ma’lumotlarni yangilab bo‘lmadi.", "Не удалось обновить данные."),
    "Loading calendar": ("Taqvim yuklanmoqda", "Календарь загружается"),
    "Publications to prepare": ("Tayyorlanadigan nashrlar", "Публикации к подготовке"),
    "Today's check-in events": (
        "Bugungi ro‘yxatdan o‘tish tadbirlari",
        "Сегодняшние мероприятия с регистрацией",
    ),
    "Private Meeting": ("Yopiq uchrashuv", "Закрытая встреча"),
    "International Events": ("Xalqaro tadbirlar", "Международные мероприятия"),
    "Approval queue": ("Tasdiqlash kutilayotgan tadbirlar", "Очередь согласования"),
    "Displaced events": ("Boshqa vaqtga ko‘chiriladigan tadbirlar", "Мероприятия для переноса"),
    "Leadership dashboard": ("Rahbariyat paneli", "Панель руководства"),
    "Super administrator": ("Bosh administrator", "Главный администратор"),
    "International department administrator": (
        "Xalqaro bo‘lim administratori",
        "Администратор международного отдела",
    ),
    "Responsible employee": ("Mas’ul xodim", "Ответственный сотрудник"),
    "Management responsible": ("Rahbariyat vakili", "Ответственный руководитель"),
    "Leadership viewer": ("Rahbariyat kuzatuvchisi", "Наблюдатель руководства"),
    "Content manager": ("Kontent menejeri", "Контент-менеджер"),
    "Reception operator": ("Qabul operatori", "Оператор приёма"),
    "International Events Management System": (
        "Xalqaro tadbirlarni boshqarish tizimi",
        "Система управления международными мероприятиями",
    ),
    "Public navigation": ("Ommaviy navigatsiya", "Публичная навигация"),
    "Live dashboard": ("Jonli panel", "Панель в реальном времени"),
    "Staff sign in": ("Xodimlar kirishi", "Вход для сотрудников"),
    "Workspace": ("Ish maydoni", "Рабочее пространство"),
    "Official international events information": (
        "Xalqaro tadbirlar bo‘yicha rasmiy ma’lumot",
        "Официальная информация о международных мероприятиях",
    ),
    "Live events dashboard": ("Tadbirlar jonli paneli", "Панель мероприятий в реальном времени"),
    "Live institutional schedule": (
        "Muassasaning jonli jadvali",
        "Расписание учреждения в реальном времени",
    ),
    "International events, clearly coordinated.": (
        "Xalqaro tadbirlar — aniq muvofiqlashtirilgan.",
        "Международные мероприятия — чётко скоординированы.",
    ),
    (
        "A public, real-time overview of today's programme, active venues "
        "and upcoming international events."
    ): (
        "Bugungi dastur, faol zallar va yaqinlashayotgan xalqaro "
        "tadbirlarning ochiq jonli ko‘rinishi.",
        "Публичный обзор сегодняшней программы, активных залов и "
        "предстоящих международных мероприятий.",
    ),
    "Current time in Tashkent": ("Toshkentdagi joriy vaqt", "Текущее время в Ташкенте"),
    "Today at a glance": ("Bugungi qisqa ko‘rinish", "Сегодня в цифрах"),
    "In progress": ("Davom etmoqda", "Идёт сейчас"),
    "right now": ("hozir", "сейчас"),
    "Starting soon": ("Tez orada boshlanadi", "Скоро начнётся"),
    "within one hour": ("bir soat ichida", "в течение часа"),
    "Active venues": ("Faol zallar", "Активные залы"),
    "monitored": ("kuzatuvda", "под наблюдением"),
    "Live operations": ("Jonli operatsiyalar", "Текущие операции"),
    "Venue status": ("Zallar holati", "Статус залов"),
    "View all venues": ("Barcha zallar", "Все залы"),
    "No active venues": ("Faol zallar yo‘q", "Нет активных залов"),
    "Venue status will appear when active venues are configured.": (
        "Faol zallar sozlangach, ularning holati shu yerda ko‘rinadi.",
        "Статус появится после настройки активных залов.",
    ),
    "Programme timeline": ("Dastur vaqt jadvali", "Хронология программы"),
    "Open calendar": ("Taqvimni ochish", "Открыть календарь"),
    "No public events today": ("Bugun ochiq tadbirlar yo‘q", "Сегодня нет публичных мероприятий"),
    "The next published programme will appear here.": (
        "Keyingi e’lon qilingan dastur shu yerda ko‘rinadi.",
        "Следующая опубликованная программа появится здесь.",
    ),
    "Next seven days": ("Keyingi yetti kun", "Следующие семь дней"),
    "No upcoming public events.": (
        "Yaqin kunlarda ochiq tadbirlar yo‘q.",
        "Предстоящих публичных мероприятий нет.",
    ),
    "Live data refreshes automatically.": (
        "Jonli ma’lumot avtomatik yangilanadi.",
        "Данные обновляются автоматически.",
    ),
    "Available for scheduling": ("Rejalashtirish uchun bo‘sh", "Доступен для планирования"),
    "Live venues": ("Jonli zallar", "Залы в реальном времени"),
    "Operational visibility": ("Operativ ko‘rinish", "Оперативная видимость"),
    "Live venue status": ("Zallarning jonli holati", "Статус залов в реальном времени"),
    "Current availability and the next public programme item for each active venue.": (
        "Har bir faol zalning joriy bandligi va keyingi ochiq dasturi.",
        "Текущая доступность и следующий публичный пункт программы каждого активного зала.",
    ),
    "Public event calendar": ("Ochiq tadbirlar taqvimi", "Календарь публичных мероприятий"),
    "Published schedule": ("E’lon qilingan jadval", "Опубликованное расписание"),
    "International events calendar": (
        "Xalqaro tadbirlar taqvimi",
        "Календарь международных мероприятий",
    ),
    "Explore public events by date, venue, type and status.": (
        "Ochiq tadbirlarni sana, zal, tur va holat bo‘yicha ko‘ring.",
        "Просматривайте публичные мероприятия по дате, залу, типу и статусу.",
    ),
    "Previous period": ("Oldingi davr", "Предыдущий период"),
    "Next period": ("Keyingi davr", "Следующий период"),
    "All venues": ("Barcha zallar", "Все залы"),
    "All types": ("Barcha turlar", "Все типы"),
    "All statuses": ("Barcha holatlar", "Все статусы"),
    "Open public event page": (
        "Tadbirning ochiq sahifasini ochish",
        "Открыть публичную страницу мероприятия",
    ),
    "Venue occupied": ("Zal band", "Зал занят"),
    "Private meeting": ("Yopiq uchrashuv", "Закрытая встреча"),
    "My workspace": ("Mening ish maydonim", "Моё рабочее пространство"),
    "My events": ("Mening tadbirlarim", "Мои мероприятия"),
    "Operations": ("Operatsiyalar", "Операции"),
    "Communication": ("Aloqa", "Коммуникации"),
    "Insights": ("Tahlil", "Аналитика"),
    "System operational": ("Tizim ishlamoqda", "Система работает"),
    "Phase 11 interface": ("11-bosqich interfeysi", "Интерфейс этапа 11"),
    "Coordinated events workspace": (
        "Muvofiqlashtirilgan tadbirlar maydoni",
        "Рабочая среда координации мероприятий",
    ),
    "Public view": ("Ochiq ko‘rinish", "Публичный вид"),
    "Role-aware workspace": ("Rolga mos ish maydoni", "Рабочее пространство по роли"),
    "Your priorities, upcoming events and required actions in one focused view.": (
        "Ustuvor vazifalar, yaqin tadbirlar va kerakli harakatlar bitta aniq ko‘rinishda.",
        "Приоритеты, предстоящие мероприятия и необходимые действия в одном представлении.",
    ),
    "Plan new event": ("Yangi tadbir rejalash", "Запланировать мероприятие"),
    "Needs action": ("Harakat talab qiladi", "Требует действий"),
    "Pending approval": ("Tasdiq kutilmoqda", "Ожидает согласования"),
    "Unread notifications": ("O‘qilmagan bildirishnomalar", "Непрочитанные уведомления"),
    "Your schedule": ("Sizning jadvalingiz", "Ваше расписание"),
    "Your schedule is clear": ("Jadvalingiz bo‘sh", "Ваше расписание свободно"),
    "Assigned and upcoming events will appear here.": (
        "Biriktirilgan va yaqin tadbirlar shu yerda ko‘rinadi.",
        "Назначенные и предстоящие мероприятия появятся здесь.",
    ),
    "Quick access": ("Tezkor kirish", "Быстрый доступ"),
    "Tools for your role": ("Rolingiz uchun vositalar", "Инструменты для вашей роли"),
    "Internal calendar": ("Ichki taqvim", "Внутренний календарь"),
    "Telegram settings": ("Telegram sozlamalari", "Настройки Telegram"),
    "Profile and language": ("Profil va til", "Профиль и язык"),
    "Profile": ("Profil", "Профиль"),
    "Account control": ("Hisob boshqaruvi", "Управление учётной записью"),
    "Profile and preferences": ("Profil va sozlamalar", "Профиль и настройки"),
    "Manage your identity and interface language. Access role changes require an administrator.": (
        "Shaxsiy ma’lumot va interfeys tilini boshqaring. Rolni faqat administrator o‘zgartiradi.",
        "Управляйте личными данными и языком интерфейса. Роль изменяет только администратор.",
    ),
    "Preferred language": ("Afzal til", "Предпочитаемый язык"),
    "Profile updated successfully.": (
        "Profil muvaffaqiyatli yangilandi.",
        "Профиль успешно обновлён.",
    ),
    "Save profile": ("Profilni saqlash", "Сохранить профиль"),
    "Access": ("Kirish huquqi", "Доступ"),
    "Role and permissions are managed centrally.": (
        "Rol va huquqlar markaziy boshqariladi.",
        "Роль и разрешения управляются централизованно.",
    ),
    "Assigned events": ("Biriktirilgan tadbirlar", "Назначенные мероприятия"),
    "Management events": ("Boshqaruv tadbirlari", "Мероприятия руководства"),
    "Boshqaruv markazi": ("Boshqaruv markazi", "Центр управления"),
    "Management": ("Boshqaruv", "Управление"),
    "Overview": ("Bosh sahifa", "Обзор"),
    "Events": ("Tadbirlar", "Мероприятия"),
    "All events": ("Barcha tadbirlar", "Все мероприятия"),
    "Rescheduling": ("Ko‘chirilganlar", "Переносы"),
    "Programs": ("Dasturlar", "Программы"),
    "Reference data": ("Ma’lumotnomalar", "Справочники"),
    "Users": ("Foydalanuvchilar", "Пользователи"),
    "Staff": ("Xodimlar", "Сотрудники"),
    "Roles": ("Rollar", "Роли"),
    "Analytics": ("Analitika", "Аналитика"),
    "System": ("Tizim", "Система"),
    "Audit log": ("Audit jurnali", "Журнал аудита"),
    "Control center": ("Boshqaruv markazi", "Центр управления"),
    "IEMS Control Center": ("IEMS boshqaruv markazi", "Центр управления IEMS"),
    "Manage the system, events and international activity from one place.": (
        "Tizim, tadbirlar va xalqaro faoliyatni yagona markazdan boshqaring.",
        "Управляйте системой, мероприятиями и международной деятельностью из единого центра.",
    ),
    "Live operational context and secure administrative tools.": (
        "Jonli operativ holat va xavfsiz boshqaruv vositalari.",
        "Оперативная обстановка и защищённые инструменты управления.",
    ),
    "System indicators": ("Tizim ko‘rsatkichlari", "Показатели системы"),
    "registered in IEMS": ("IEMS tizimida ro‘yxatdan o‘tgan", "зарегистрировано в IEMS"),
    "Today's events": ("Bugungi tadbirlar", "Сегодняшние мероприятия"),
    "on today's schedule": ("bugungi jadvalda", "в расписании на сегодня"),
    "Awaiting approval": ("Tasdiqlash kutilmoqda", "Ожидают согласования"),
    "requires a decision": ("qaror talab qiladi", "требуют решения"),
    "available to the system": ("tizimda faol", "активны в системе"),
    "Today's attendance": ("Bugungi qatnashuv", "Посещаемость сегодня"),
    "recorded check-ins": ("qayd etilgan kirishlar", "зарегистрированных отметок"),
    "Quick actions": ("Tezkor amallar", "Быстрые действия"),
    "Start a common task": ("Asosiy vazifani boshlang", "Начните основную задачу"),
    "New event": ("Yangi tadbir", "Новое мероприятие"),
    "Plan and assign": ("Rejalash va biriktirish", "Планирование и назначение"),
    "Add speaker": ("Spiker qo‘shish", "Добавить спикера"),
    "Create profile": ("Profil yaratish", "Создать профиль"),
    "Add organization": ("Tashkilot qo‘shish", "Добавить организацию"),
    "Register partner": ("Hamkorni ro‘yxatga olish", "Зарегистрировать партнёра"),
    "Add venue": ("Zal qo‘shish", "Добавить зал"),
    "Configure space": ("Maydonni sozlash", "Настроить пространство"),
    "Review schedule": ("Jadvalni ko‘rish", "Просмотреть расписание"),
    "Operational insight": ("Operativ tahlil", "Оперативная аналитика"),
    "Administration": ("Administratsiya", "Администрирование"),
    "System modules": ("Tizim modullari", "Модули системы"),
    "awaiting approval": ("tasdiqlash kutilmoqda", "ожидают согласования"),
    "active spaces": ("faol zal", "активных залов"),
    "Manage venues": ("Zallarni boshqarish", "Управление залами"),
    "Display access": ("Ekran kirishi", "Доступ к экранам"),
    "Partners and sponsors": ("Hamkorlar va homiylar", "Партнёры и спонсоры"),
    "Users and access": ("Foydalanuvchilar va kirish", "Пользователи и доступ"),
    "Staff accounts and roles": ("Xodim hisoblari va rollar", "Учётные записи и роли"),
    "Communications": ("Kommunikatsiyalar", "Коммуникации"),
    "Telegram and publications": ("Telegram va nashrlar", "Telegram и публикации"),
    "Telegram deliveries": ("Telegram yuborishlari", "Отправки Telegram"),
    "Governance": ("Nazorat", "Контроль"),
    "Attendance and audit history": ("Davomat va audit tarixi", "Посещаемость и история аудита"),
    "Recent changes": ("So‘nggi harakatlar", "Последние изменения"),
    "No new activity yet": ("Hozircha yangi harakat yo‘q", "Новых действий пока нет"),
    "Administrative changes will appear here.": (
        "Ma’muriy o‘zgarishlar shu yerda ko‘rinadi.",
        "Административные изменения появятся здесь.",
    ),
    "Manage all international events": (
        "Barcha xalqaro tadbirlarni boshqarish",
        "Управление всеми международными мероприятиями",
    ),
    "Search, filter and manage permitted records.": (
        "Ruxsat etilgan yozuvlarni qidiring, filtrlang va boshqaring.",
        "Ищите, фильтруйте и управляйте разрешёнными записями.",
    ),
    "Clear filters": ("Filtrlarni tozalash", "Очистить фильтры"),
    "Active": ("Faol", "Активные"),
    "New record": ("Yangi yozuv", "Новая запись"),
    "Complete the fields below. Required information is clearly marked.": (
        "Quyidagi maydonlarni to‘ldiring. Majburiy ma’lumotlar aniq belgilangan.",
        "Заполните поля ниже. Обязательные данные чётко обозначены.",
    ),
    "Basic information": ("Asosiy ma’lumotlar", "Основная информация"),
    "Schedule and venue": ("Jadval va zal", "Расписание и зал"),
    "Responsible persons and partners": ("Mas’ullar va hamkorlar", "Ответственные и партнёры"),
    "Public information and attendance": (
        "Ochiq ma’lumot va davomat",
        "Публичная информация и посещаемость",
    ),
    "Workflow": ("Ish jarayoni", "Рабочий процесс"),
    "Reminder policy": ("Eslatma siyosati", "Правила напоминаний"),
    "System metadata": ("Tizim ma’lumotlari", "Системные данные"),
    "Choose a module to view and manage permitted records.": (
        "Ruxsat etilgan yozuvlarni ko‘rish va boshqarish uchun modulni tanlang.",
        "Выберите модуль для просмотра и управления разрешёнными записями.",
    ),
    "Secure administrative records": (
        "Himoyalangan ma’muriy yozuvlar",
        "Защищённые административные записи",
    ),
    "View records": ("Yozuvlarni ko‘rish", "Просмотреть записи"),
    "Add new": ("Yangi qo‘shish", "Добавить"),
    "Audit trail": ("O‘zgarishlar jurnali", "Журнал изменений"),
    "Change history": ("O‘zgarishlar tarixi", "История изменений"),
    "No change history": ("O‘zgarishlar tarixi yo‘q", "История изменений отсутствует"),
    "Changes to this record will appear here.": (
        "Ushbu yozuvdagi o‘zgarishlar shu yerda ko‘rinadi.",
        "Изменения этой записи появятся здесь.",
    ),
    "Event": ("Tadbir", "Мероприятие"),
    "Date / time": ("Sana / vaqt", "Дата / время"),
    "Venue": ("Zal", "Зал"),
    "Type": ("Turi", "Тип"),
    "Responsible": ("Mas’ul", "Ответственный"),
    "Status": ("Holat", "Статус"),
    "Filters": ("Filtrlar", "Фильтры"),
    "Search by event title, organization or responsible person…": (
        "Tadbir nomi, tashkilot yoki mas’ul bo‘yicha qidirish…",
        "Поиск по названию, организации или ответственному…",
    ),
    "Search records…": ("Yozuvlarni qidirish…", "Поиск записей…"),
    "Normal": ("Oddiy", "Обычный"),
    "Cancelled": ("Bekor qilingan", "Отменено"),
    "Pending Approval": ("Tasdiqlash kutilmoqda", "Ожидает согласования"),
    "Planned Events": ("Rejalashtirilgan tadbirlar", "Запланированные мероприятия"),
    "Schedule and manage international events across university venues.": (
        "Xalqaro tadbirlarni rejalashtiring va boshqaring.",
        "Планируйте международные мероприятия и управляйте ими.",
    ),
    "Plan New Event": ("Yangi tadbir", "Новое мероприятие"),
    "Search by event title or description...": (
        "Tadbir nomi yoki tavsifi bo‘yicha qidirish...",
        "Поиск по названию или описанию мероприятия...",
    ),
    "All Statuses": ("Barcha holatlar", "Все статусы"),
    "All Venues": ("Barcha zallar", "Все залы"),
    "All Types": ("Barcha turlar", "Все типы"),
    "Event Type": ("Turi", "Тип"),
    "Date & Weekday": ("Sana", "Дата"),
    "Time": ("Vaqt", "Время"),
    "Actions": ("Amallar", "Действия"),
    "View": ("Ko‘rish", "Просмотр"),
    "Edit": ("Tahrirlash", "Изменить"),
    "Cancel": ("Bekor qilish", "Отменить"),
    "No events found": ("Tadbirlar topilmadi", "Мероприятия не найдены"),
    "Try adjusting your search query or filters.": (
        "Qidiruv yoki filtrlarni o‘zgartirib ko‘ring.",
        "Измените поисковый запрос или фильтры.",
    ),
    "Plan an Event": ("Yangi tadbir yaratish", "Создать мероприятие"),
    "Clear": ("Tozalash", "Очистить"),
    "System active": ("Tizim faol", "Система активна"),
    "Operational": ("Ishlamoqda", "Работает"),
    "%(minutes)s minutes remaining": (
        "Tugashiga %(minutes)s daqiqa",
        "До завершения %(minutes)s мин.",
    ),
    "Starts in %(minutes)s minutes": (
        "%(minutes)s daqiqadan keyin boshlanadi",
        "Начало через %(minutes)s мин.",
    ),
    "Free until": ("Bo‘sh, keyingi tadbir", "Свободен до"),
    "Public dashboard": ("Ochiq panel", "Публичная панель"),
    "Today's timeline": ("Bugungi vaqt jadvali", "Расписание на сегодня"),
    "No events scheduled today": ("Bugun tadbir rejalashtirilmagan", "Сегодня мероприятий нет"),
    "No events awaiting approval": (
        "Tasdiqlash kutilayotgan tadbir yo‘q",
        "Нет мероприятий на согласовании",
    ),
    "Live": ("Jonli", "Онлайн"),
    "System online": ("Tizim onlayn", "Система онлайн"),
    "Tashkent operational time": ("Toshkent operatsion vaqti", "Операционное время Ташкента"),
    "Search": ("Qidirish", "Поиск"),
    "Search events": ("Tadbirlarni qidirish", "Поиск мероприятий"),
    "Reset": ("Tiklash", "Сбросить"),
    "Responsible person": ("Mas’ul shaxs", "Ответственное лицо"),
    "Organization": ("Tashkilot", "Организация"),
    "No events planned": ("Tadbir rejalashtirilmagan", "Мероприятий нет"),
    "Republican Oncology Center and Gustave Roussy International Uzbekistan": (
        "Respublika onkologiya markazi va Gustave Roussy International Uzbekistan",
        "Республиканский онкологический центр и Gustave Roussy International Uzbekistan",
    ),
    "Republic Oncology Center": (
        "Respublika onkologiya markazi",
        "Республиканский онкологический центр",
    ),
}


def main() -> None:
    root = Path(__file__).resolve().parents[1] / "locale"
    for language, index in (("uz", 0), ("ru", 1), ("en", None)):
        po_path = root / language / "LC_MESSAGES" / "django.po"
        catalog = polib.pofile(str(po_path))
        for msgid, localized in TRANSLATIONS.items():
            msgstr = msgid if index is None else localized[index]
            entry = catalog.find(msgid)
            if entry:
                entry.msgstr = msgstr
            else:
                catalog.append(polib.POEntry(msgid=msgid, msgstr=msgstr))
        catalog.save(str(po_path))
        catalog.save_as_mofile(str(po_path.with_suffix(".mo")))


if __name__ == "__main__":
    main()
