# Generated by Django 5.2.16 on 2026-08-13 09:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_event_checkin_closes_at_event_checkin_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='checked in at')),
                ('checkin_method', models.CharField(choices=[('public_qr', 'Public QR'), ('staff_manual', 'Staff Manual'), ('registration_import', 'Registration Import'), ('invitation', 'Invitation'), ('kiosk', 'Kiosk')], default='public_qr', max_length=32, verbose_name='check-in method')),
                ('attendee_identifier_hash', models.CharField(db_index=True, max_length=64, verbose_name='attendee identifier hash')),
                ('attendee_name', models.CharField(blank=True, default='', max_length=255, verbose_name='full name')),
                ('attendee_organization', models.CharField(blank=True, default='', max_length=255, verbose_name='organization')),
                ('attendee_role', models.CharField(blank=True, default='', max_length=255, verbose_name='role / title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'event attendance',
                'verbose_name_plural': 'event attendances',
                'ordering': ('-checked_in_at',),
                'constraints': [models.UniqueConstraint(fields=('event', 'attendee_identifier_hash'), name='unique_event_attendee_hash')],
            },
        ),
    ]
