# Generated by Django 5.2.16 on 2026-08-12 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('event.created', 'Event Created'), ('event.updated', 'Event Updated'), ('event.planned', 'Event Planned'), ('event.cancelled', 'Event Cancelled')], max_length=64, verbose_name='action')),
                ('target_id', models.CharField(blank=True, max_length=128, verbose_name='target ID')),
                ('target_repr', models.CharField(blank=True, max_length=255, verbose_name='target representation')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ('-timestamp',),
            },
        ),
    ]
