# Generated by Django 5.2.16 on 2026-08-12 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditeventlog',
            name='action',
            field=models.CharField(choices=[('event.created', 'Event Created'), ('event.updated', 'Event Updated'), ('event.planned', 'Event Planned'), ('event.cancelled', 'Event Cancelled'), ('event.submitted', 'Event Submitted for Approval'), ('event.approved', 'Event Approved'), ('event.rejected', 'Event Rejected'), ('event.resubmitted', 'Event Resubmitted'), ('event.displaced', 'Event Displaced by Emergency'), ('event.emergency_override', 'Emergency Override Executed')], max_length=64, verbose_name='action'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_audit_action_947529_idx'),
        ),
        migrations.AddIndex(
            model_name='auditeventlog',
            index=models.Index(fields=['target_id', 'action'], name='audit_audit_target__9880fb_idx'),
        ),
    ]
