# Generated by Django 5.2.16 on 2026-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditeventlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditeventlog',
            name='action',
            field=models.CharField(choices=[('event.created', 'Event Created'), ('event.updated', 'Event Updated'), ('event.planned', 'Event Planned'), ('event.cancelled', 'Event Cancelled'), ('event.submitted', 'Event Submitted for Approval'), ('event.approved', 'Event Approved'), ('event.rejected', 'Event Rejected'), ('event.resubmitted', 'Event Resubmitted'), ('event.postponed', 'Event Postponed'), ('event.rescheduled', 'Event Rescheduled'), ('event.emergency_requested', 'Emergency Requested'), ('event.emergency_overridden', 'Emergency Override Executed'), ('event.emergency_override', 'Emergency Override Executed'), ('event.displaced', 'Event Displaced by Emergency')], max_length=64, verbose_name='action'),
        ),
    ]
