# Generated by Django 5.2.16 on 2026-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditeventlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditeventlog',
            name='action',
            field=models.CharField(choices=[('event.created', 'Event Created'), ('event.updated', 'Event Updated'), ('event.planned', 'Event Planned'), ('event.cancelled', 'Event Cancelled'), ('event.submitted', 'Event Submitted for Approval'), ('event.approved', 'Event Approved'), ('event.rejected', 'Event Rejected'), ('event.resubmitted', 'Event Resubmitted'), ('event.postponed', 'Event Postponed'), ('event.rescheduled', 'Event Rescheduled'), ('event.emergency_requested', 'Emergency Requested'), ('event.emergency_overridden', 'Emergency Override Executed'), ('event.emergency_override', 'Emergency Override Executed'), ('event.displaced', 'Event Displaced by Emergency'), ('event.program_source_changed', 'Program Source Changed'), ('event.program_pdf_uploaded', 'Program PDF Uploaded'), ('event.program_pdf_replaced', 'Program PDF Replaced'), ('event.program_pdf_removed', 'Program PDF Removed'), ('event.program_item_added', 'Program Item Added'), ('event.program_item_updated', 'Program Item Updated'), ('event.program_item_removed', 'Program Item Removed'), ('event.public_page_enabled', 'Public Page Enabled'), ('event.public_token_rotated', 'Public Token Rotated'), ('event.qr_generated', 'QR Code Generated'), ('event.qr_printed', 'QR Code Printed'), ('display.token_created', 'Display Token Created'), ('display.token_rotated', 'Display Token Rotated'), ('display.enabled', 'Display Enabled'), ('display.disabled', 'Display Disabled'), ('telegram.connection_created', 'Telegram Connected'), ('telegram.connection_removed', 'Telegram Disconnected'), ('telegram.test_sent', 'Telegram Test Sent'), ('telegram.reminder_scheduled', 'Telegram Reminder Scheduled'), ('telegram.reminder_sent', 'Telegram Reminder Sent'), ('telegram.reminder_failed', 'Telegram Reminder Failed'), ('telegram.event_notification_sent', 'Telegram Event Notification Sent'), ('publication.created', 'Publication Created'), ('publication.updated', 'Publication Updated'), ('publication.approved', 'Publication Approved'), ('publication.scheduled', 'Publication Scheduled'), ('publication.published', 'Publication Published'), ('publication.failed', 'Publication Failed'), ('publication.cancelled', 'Publication Cancelled'), ('publication.retried', 'Publication Retried'), ('banner.generated', 'Banner Generated'), ('banner.regenerated', 'Banner Regenerated')], max_length=64, verbose_name='action'),
        ),
    ]
