# Generated by Django 5.2.16 on 2026-08-12 11:40

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='code')),
                ('name_uz', models.CharField(max_length=160, verbose_name='name in Uzbek')),
                ('name_ru', models.CharField(max_length=160, verbose_name='name in Russian')),
                ('name_en', models.CharField(max_length=160, verbose_name='name in English')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacity')),
                ('working_start', models.TimeField(verbose_name='working start')),
                ('working_end', models.TimeField(verbose_name='working end')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_enabled', models.BooleanField(default=True, verbose_name='display enabled')),
                ('photo', models.FileField(blank=True, upload_to='venues/%Y/%m/', validators=[config.validators.validate_image_upload], verbose_name='photo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'venue',
                'verbose_name_plural': 'venues',
                'ordering': ('sort_order', 'code'),
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='venue_capacity_positive'), models.CheckConstraint(condition=models.Q(('working_end__gt', models.F('working_start'))), name='venue_working_hours_ordered')],
            },
        ),
    ]
