# Generated by Django 5.2.16 on 2026-08-13 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='display token')),
                ('name', models.CharField(max_length=100, verbose_name='display name / location')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
            ],
            options={
                'verbose_name': 'display token',
                'verbose_name_plural': 'display tokens',
                'ordering': ('name',),
            },
        ),
    ]
