# Generated by Django 5.2.16 on 2026-08-13 10:07

import apps.venues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_displaytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaytoken',
            name='token',
            field=models.CharField(db_index=True, default=apps.venues.models.generate_display_token, editable=False, max_length=64, unique=True, verbose_name='display token'),
        ),
    ]
