# Generated by Django 5.2.16 on 2026-08-12 11:40

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='short name')),
                ('organization_type', models.CharField(choices=[('local', 'Local organization'), ('foreign', 'Foreign organization'), ('partner', 'Partner organization')], default='local', max_length=16, verbose_name='organization type')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=48, verbose_name='phone')),
                ('contact_person', models.CharField(blank=True, max_length=160, verbose_name='contact person')),
                ('logo', models.FileField(blank=True, upload_to='organizations/%Y/%m/', validators=[config.validators.validate_image_upload], verbose_name='logo')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'organization_type'], name='organizatio_is_acti_37d082_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('contact_person', models.CharField(blank=True, max_length=160, verbose_name='contact person')),
                ('phone', models.CharField(blank=True, max_length=48, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('logo', models.FileField(blank=True, upload_to='sponsors/%Y/%m/', validators=[config.validators.validate_image_upload], verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsors',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active'], name='organizatio_is_acti_935433_idx')],
            },
        ),
    ]
