# Generated by Django 5.2.16 on 2026-10-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_phone_alter_sponsor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, verbose_name='notes'),
        ),
    ]
