# Generated by Django 5.2.16 on 2026-08-25 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_telegramconnection_telegramdelivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, default='', max_length=64, verbose_name='chat ID')),
                ('label', models.CharField(blank=True, default='', max_length=120, verbose_name='label')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram channel settings',
                'verbose_name_plural': 'Telegram channel settings',
            },
        ),
    ]
